SELECT 
    UU.USER_ID,
    UU.NICKNAME,
    CONCAT(UU.CITY, ' ', UU.STREET_ADDRESS1, ' ', UU.STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTR(UU.TLNO, 1, 3), '-', SUBSTR(UU.TLNO, 4, 4), '-', SUBSTR(UU.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD UG
JOIN USED_GOODS_USER UU
ON UG.WRITER_ID = UU.USER_ID
GROUP BY 
    UU.USER_ID,
    UU.NICKNAME,
    UU.CITY,
    UU.STREET_ADDRESS1,
    UU.STREET_ADDRESS2,
    UU.TLNO
HAVING COUNT(UG.WRITER_ID) >= 3
ORDER BY UU.USER_ID DESC;