SELECT DISTINCT CC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
ON CC.CAR_ID = CH.CAR_ID
WHERE MONTH(CH.START_DATE) = 10 AND CC.CAR_TYPE = '세단'
ORDER BY CC.CAR_ID DESC;